### ISSUE TITLE
Non-null terminated C string in openosc_get_process_name

### ISSUE THREAD

**Issue by ariel-miculas** [cisco/OpenOSC#5]
https://github.com/cisco/OpenOSC/blob/master/src/openosc_support.c#L58-L62
If the last character from `/proc/%d/cmdline` is not '\n', the string will not be NUL terminated.
Found by @hallyn

**Comment by yonhan3** [comment]
Thanks for reporting this issue.
Yes, this function will return non-NULL terminated string in some cases.
However, since this function is a static function, which is only used by another function in this same file at line 104. And the other function does make it NULL terminated at line 109. So the impact is limited.
But I will try to improve this function in next release of OpenOSC.

**Comment by yonhan3** [comment]
Yes, agree. I will fix the get_process_name function to always return NULL-terminated string.

**Comment by yonhan3** [comment]
This issue has been fixed by commit #6
The new v1.0.7 version has the fix.

**Comment by hallyn** [comment]
The 'commit #6' above is not right: since you're not using pull requests, github just links it to issue #6, which does not exist.

The correct commit is, I assume:

https://github.com/cisco/OpenOSC/commit/d1bd20c332c48d37d67ba8eb2f1167b86150e135

**Comment by yonhan3** [comment]
Yes, you are right. Thanks for pointing this out. :-)
